version: '3.8'

services:
  keymaster-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keymaster-app
    ports:
      - "8082:8082"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

